# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: WORKDIR /app

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: FROM node:9

      # Runs a set of commands using the runners shell
      - name: Install app dependencies
        run: COPY package*.json ./
        
      - name: Run npm install
        run: RUN npm install
     
      - name: Copying rest of the application to app directory
        run: COPY . /app

      - name: Expose the port and start the application
        run: Expose 9090

CMD ["npm","start"]

